server:
  port: ${port:8000}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true 
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.cimknwts3ktb.ap-northeast-2.rds.amazonaws.com:3306/worksout?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
   
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
          
    
mybatis:
  mapper-locations:
  - /mappers/*.xml

file:
  path: C:/TeamProject/workspace/git/worksout-TeamProject/upload/
  downloadPath:  C:/TeamProject/workspace/git/worksout-TeamProject/download/
  
